# Data Analysis Techniques. Lab 5. Working with `pandas`, part 2.

# 1. Data selection

While statistics for an entire series or dataframe are useful, we are often interested in various subsets of data and their properties, which requires understanding (including by analogy with subsets we have already examined) the mechanisms for retrieving and filtering data in pandas. First, however, we will load the necessary data.

In the examples below, you should update the data path to match your local file storage structure.

In [7]:
import pandas as pd
import os

In [8]:
# if the data folder is inside the same folder as your notebook
DATAPATH = '/content/loan_data.csv'

In [9]:
# link to the original dataset: https://www.kaggle.com/datasets/udaymalviya/bank-loan-data
df = pd.read_csv(os.path.join(DATAPATH, '/content/loan_data.csv'))

In [10]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561.0,No,1.0
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504.0,Yes,0.0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635.0,No,1.0
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675.0,No,1.0
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586.0,No,1.0

## 1.1 Selecting columns from pandas dataframe

In [11]:
# single column selection - we provide a name for a column as we search for a value in dictionary
# by providing a key name
df['person_gender']

0        female
1        female
2        female
3        female
4          male
          ...
26252    female
26253    female
26254    female
26255    female
26256      male
Name: person_gender, Length: 26257, dtype: object

In [12]:
# selecting many columns is also possible by providing a list of column names
df[['person_gender','person_education']]

      person_gender person_education
0            female           Master
1            female      High School
2            female      High School
3            female         Bachelor
4              male           Master
...             ...              ...
26252        female      High School
26253        female         Bachelor
26254        female         Bachelor
26255        female         Bachelor
26256          male         Bachelor

[26257 rows x 2 columns]

In [13]:
# We can also access data in a column using the dot operator
# depending on whether the column names contain whitespace or not
df.person_gender

0        female
1        female
2        female
3        female
4          male
          ...
26252    female
26253    female
26254    female
26255    female
26256      male
Name: person_gender, Length: 26257, dtype: object

In [14]:
# after selecting single (pandas Series) or multiple columns (pandas dataFrame) part we
# can use indexing or slicing to get ROWS that we are interested in
df['person_gender'][:5]

0    female
1    female
2    female
3    female
4      male
Name: person_gender, dtype: object

In [15]:
df[['person_gender','person_education']][:5]

  person_gender person_education
0        female           Master
1        female      High School
2        female      High School
3        female         Bachelor
4          male           Master

## 1.2 Selecting data using `.loc`, `.iloc`, and mapping with a boolean array

`.loc` uses label-based indexing, but you can also pass a boolean array. Labels refer to the values in the index column of a pandas series or pandas DataFrame, or the column names in a pandas DataFrame.

In [16]:
# as pandas DataFrame is a two dimensional data type - we have two dimensions to provide indexes or slices for
# data selection
df.loc[:, 'person_gender']

0        female
1        female
2        female
3        female
4          male
          ...
26252    female
26253    female
26254    female
26255    female
26256      male
Name: person_gender, Length: 26257, dtype: object

In [17]:
# We can also specify a value for only one dimension
# Here, we're looking for rows (default axis) where the “index” column has a value of 1, 2, or 3
df.loc[[1,2,3]]

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504.0,Yes,0.0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635.0,No,1.0
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675.0,No,1.0

In [18]:
df.loc[:5, ['person_gender', 'person_income']]

  person_gender  person_income
0        female        71948.0
1        female        12282.0
2        female        12438.0
3        female        79753.0
4          male        66135.0
5        female        12951.0

In [19]:
# Note that the value for the first dimension (loc) is the actual value in the index column,
# not the index number of the elements in that index.
# Below is an example where the index has been changed to values starting from 1.
df.index = range(1, df.shape[0] + 1)

In [20]:
df[:5]

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561.0,No,1.0
2,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504.0,Yes,0.0
3,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635.0,No,1.0
4,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675.0,No,1.0
5,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586.0,No,1.0

In [21]:
# now we are checking how loc works with the same parameters as iloc
df.loc[:5, ['person_gender', 'person_income']]

  person_gender  person_income
1        female        71948.0
2        female        12282.0
3        female        12438.0
4        female        79753.0
5          male        66135.0

**WARNING!**

Indexing using labels is performed with the stop value included, which is different from how classic slices work in Python!

Indexing with `.iloc` is similar to `.loc`, but here the letter `i` represents an index, so instead of column and row labels, we specify indices.

In [22]:
# row indexes: 0-4, column indexes: 2 and 3
df.iloc[:5, 2:4]

  person_education  person_income
1           Master        71948.0
2      High School        12282.0
3      High School        12438.0
4         Bachelor        79753.0
5           Master        66135.0

In [23]:
# Just like with the NumPy library, we can also manipulate the data in these areas, such as swapping the order of the columns
# although this isn’t usually necessary, since we can retrieve data from the frame in any column order
# Here’s the column order: third, second, and fourth columns (remember that indexing starts at 0?)
df.iloc[:, [2,1, 3]]

      person_education person_gender  person_income
1               Master        female        71948.0
2          High School        female        12282.0
3          High School        female        12438.0
4             Bachelor        female        79753.0
5               Master          male        66135.0
...                ...           ...            ...
26253      High School        female        91131.0
26254         Bachelor        female        75625.0
26255         Bachelor        female       120932.0
26256         Bachelor        female        68809.0
26257         Bachelor          male        76472.0

[26257 rows x 3 columns]

In [24]:
# However, if we wanted to reorder them in the original grid, we could, for example, use the vector
# of the current column names from the .columns property
df.columns

Index(['person_age', 'person_gender', 'person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_intent',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file', 'loan_status'],
      dtype='object')

In [25]:
# Let's say we want to swap columns 2 and 3
# For simplicity, we'll store the values of these labels in a Python list
old_columns = list(df.columns)
new_column_order = old_columns[:1] + old_columns[2:0:-1] + old_columns[3:]
new_column_order

['person_age',
 'person_education',
 'person_gender',
 'person_income',
 'person_emp_exp',
 'person_home_ownership',
 'loan_amnt',
 'loan_intent',
 'loan_int_rate',
 'loan_percent_income',
 'cb_person_cred_hist_length',
 'credit_score',
 'previous_loan_defaults_on_file',
 'loan_status']

In [26]:
# Overwrite the variable with the original data frame, a new data frame with a different column order
df = df.loc[:, new_column_order]

In [27]:
df.head()

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,Master,female,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561.0,No,1.0
2,21.0,High School,female,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504.0,Yes,0.0
3,25.0,High School,female,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635.0,No,1.0
4,23.0,Bachelor,female,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675.0,No,1.0
5,24.0,Master,male,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586.0,No,1.0

**Selecting Data Using Boolean Value Tables**

This operation is typically used in data filtering, where a condition is applied to select data from a frame or series. Here, we can use the operators `|` (logical OR), `&` (logical AND), and `~` for negation.

In [28]:
# returned type - a numpy array of boolean types (a mapping)
print(df['person_gender'] == 'female')

# now we apply the mapping to the data
df[df['person_gender'] == 'female']

1         True
2         True
3         True
4         True
5        False
         ...
26253     True
26254     True
26255     True
26256     True
26257    False
Name: person_gender, Length: 26257, dtype: bool

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,Master,female,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561.0,No,1.0
2,21.0,High School,female,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504.0,Yes,0.0
3,25.0,High School,female,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635.0,No,1.0
4,23.0,Bachelor,female,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675.0,No,1.0
6,21.0,High School,female,12951.0,0,OWN,2500.0,VENTURE,7.14,0.19,2.0,532.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26250,31.0,Bachelor,female,90664.0,8,MORTGAGE,10000.0,MEDICAL,15.58,0.11,6.0,687.0,No,1.0
26253,29.0,High School,female,91131.0,8,MORTGAGE,15000.0,MEDICAL,15.33,0.16,10.0,590.0,No,1.0
26254,28.0,Bachelor,female,75625.0,7,RENT,14000.0,VENTURE,10.99,0.19,10.0,647.0,No,0.0
26255,27.0,Bachelor,female,120932.0,1,MORTGAGE,3000.0,VENTURE,12.84,0.02,10.0,695.0,Yes,0.0
26256,27.0,Bachelor,female,68809.0,3,RENT,14000.0,HOMEIMPROVEMENT,13.87,0.20,8.0,656.0,No,1.0

In [29]:
# mapping with two conditions (& - this is a logical AND operator)
(df['loan_amnt'] > 10000) & (df['person_income'] < 50000)

1        False
2        False
3        False
4        False
5        False
         ...
26253    False
26254    False
26255    False
26256    False
26257    False
Length: 26257, dtype: bool

In [30]:
# and now the data by applying the mapping
df[(df['loan_amnt'] > 10000) & (df['person_income'] < 50000)]

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
461,24.0,Associate,male,22684.0,0,OWN,13000.0,PERSONAL,7.88,0.57,3.0,640.0,No,1.0
494,23.0,Bachelor,male,43042.0,1,RENT,22250.0,DEBTCONSOLIDATION,12.69,0.52,3.0,678.0,No,1.0
536,22.0,High School,male,38473.0,0,RENT,21250.0,DEBTCONSOLIDATION,12.42,0.55,3.0,599.0,No,1.0
544,21.0,High School,male,42536.0,0,RENT,21000.0,VENTURE,12.53,0.49,4.0,687.0,No,1.0
547,26.0,Bachelor,female,48929.0,6,RENT,21000.0,MEDICAL,6.54,0.43,4.0,601.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26117,33.0,Associate,male,40597.0,9,RENT,13800.0,VENTURE,13.47,0.34,5.0,640.0,No,1.0
26131,30.0,Bachelor,female,28849.0,6,RENT,14000.0,VENTURE,7.88,0.49,6.0,614.0,No,1.0
26143,28.0,Associate,female,45584.0,5,RENT,14000.0,DEBTCONSOLIDATION,14.42,0.31,10.0,684.0,No,1.0
26147,28.0,High School,male,47754.0,8,RENT,14000.0,EDUCATION,7.90,0.29,8.0,584.0,No,1.0
26176,31.0,Bachelor,female,39461.0,8,OWN,12375.0,VENTURE,9.91,0.31,7.0,552.0,Yes,0.0

In [31]:
# and now we're completing this data by using the same condition and its negation
# an additional parenthesis has been added
df[~((df['loan_amnt'] > 10000) & (df['person_income'] < 50000))]

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,Master,female,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561.0,No,1.0
2,21.0,High School,female,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504.0,Yes,0.0
3,25.0,High School,female,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635.0,No,1.0
4,23.0,Bachelor,female,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675.0,No,1.0
5,24.0,Master,male,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26253,29.0,High School,female,91131.0,8,MORTGAGE,15000.0,MEDICAL,15.33,0.16,10.0,590.0,No,1.0
26254,28.0,Bachelor,female,75625.0,7,RENT,14000.0,VENTURE,10.99,0.19,10.0,647.0,No,0.0
26255,27.0,Bachelor,female,120932.0,1,MORTGAGE,3000.0,VENTURE,12.84,0.02,10.0,695.0,Yes,0.0
26256,27.0,Bachelor,female,68809.0,3,RENT,14000.0,HOMEIMPROVEMENT,13.87,0.20,8.0,656.0,No,1.0
26257,32.0,Bachelor,male,76472.0,7,RENT,14000.0,EDUCATION,6.00,NaN,NaN,NaN,NaN,NaN

In [32]:
# If we want to filter a column based on multiple values, it will be more useful and concise to
# use the isin() method
df['person_education'].isin(['Associate', 'High School'])

1        False
2         True
3         True
4        False
5        False
         ...
26253     True
26254    False
26255    False
26256    False
26257    False
Name: person_education, Length: 26257, dtype: bool

In [33]:
# Filtering is also possible using a callable object,
# such as a built-in function or an anonymous function (lambda)
# Here are some examples

# Here, we first access the value `str` from this series, then apply the `startswith(‘D’)` method to each
# value in the series, which returns a Boolean array
map_1 = df['loan_intent'].str.startswith('D')

# Here's the same effect, but using `apply` (which maps something to each element of an iterable object) — here we map a function
# to each value in a given data series, and additionally pass the argument ‘D’ to the mapped function
map_2 = df['loan_intent'].apply(str.startswith, args='D')

# and yet another example - this time using anonymous function (lambda)
map_3 = df['loan_intent'].map(lambda x: x.startswith('D'))

map_1, map_2, map_3

(1        False
 2        False
 3        False
 4        False
 5        False
          ...
 26253    False
 26254    False
 26255    False
 26256    False
 26257    False
 Name: loan_intent, Length: 26257, dtype: bool,
 1        False
 2        False
 3        False
 4        False
 5        False
          ...
 26253    False
 26254    False
 26255    False
 26256    False
 26257    False
 Name: loan_intent, Length: 26257, dtype: bool,
 1        False
 2        False
 3        False
 4        False
 5        False
          ...
 26253    False
 26254    False
 26255    False
 26256    False
 26257    False
 Name: loan_intent, Length: 26257, dtype: bool)

In [34]:
df[map_1]

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
16,23.0,Master,female,600891.0,5,MORTGAGE,30000.0,DEBTCONSOLIDATION,10.65,0.05,3.0,670.0,Yes,0.0
19,23.0,Bachelor,male,136628.0,0,RENT,35000.0,DEBTCONSOLIDATION,18.25,0.26,4.0,709.0,No,1.0
34,25.0,High School,female,368115.0,3,RENT,24250.0,DEBTCONSOLIDATION,13.85,0.07,3.0,567.0,Yes,0.0
38,24.0,High School,male,78026.0,3,RENT,30000.0,DEBTCONSOLIDATION,14.54,0.38,3.0,582.0,No,1.0
40,23.0,High School,female,86811.0,0,RENT,30000.0,DEBTCONSOLIDATION,11.01,0.35,4.0,602.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26205,27.0,Bachelor,male,58959.0,6,RENT,14000.0,DEBTCONSOLIDATION,13.79,0.24,10.0,619.0,No,1.0
26214,32.0,Master,female,118426.0,10,MORTGAGE,6000.0,DEBTCONSOLIDATION,8.88,0.05,10.0,663.0,No,0.0
26222,32.0,Bachelor,female,119435.0,10,MORTGAGE,5400.0,DEBTCONSOLIDATION,9.38,0.05,6.0,710.0,No,0.0
26224,34.0,High School,female,119073.0,11,MORTGAGE,2500.0,DEBTCONSOLIDATION,15.96,0.02,10.0,643.0,Yes,0.0
26243,28.0,Master,female,120238.0,8,MORTGAGE,6500.0,DEBTCONSOLIDATION,5.99,0.05,6.0,672.0,No,0.0

In [35]:
# Let's consider a scenario where we're interested in records where, after subtracting the loan amount
# from income, the remaining amount is greater than 50,000

# We can calculate this fairly easily
print(df['person_income'] - df['loan_amnt'])

# now we can use it as a condition (mapping)
netto_income_mapping = (df['person_income'] - df['loan_amnt']) > 50000
print(netto_income_mapping)

# and apply to the real data
df[netto_income_mapping]

# Can this also be done using a lambda function?

# A lambda function receives a parameter for each value returned by the iterator for the iterable
# on which it is called. In the previous case, it was a single data series, so the anonymous function received
# a single value from the series. Now let’s try another example where the function receives multiple values.

# Here, the lambda function’s argument is the entire record from the data frame; we can index it in any way
# that was presented earlier
df.apply(lambda x: (x['person_income'] - x['loan_amnt']) > 50000, axis=1)

1         36948.0
2         11282.0
3          6938.0
4         44753.0
5         31135.0
           ...
26253     76131.0
26254     61625.0
26255    117932.0
26256     54809.0
26257     62472.0
Length: 26257, dtype: float64
1        False
2        False
3        False
4        False
5        False
         ...
26253     True
26254     True
26255     True
26256     True
26257     True
Length: 26257, dtype: bool

1        False
2        False
3        False
4        False
5        False
         ...
26253     True
26254     True
26255     True
26256     True
26257     True
Length: 26257, dtype: bool

## 1.3 Using `DataFrame.query`

In addition to the examples shown above, there is also the `query` method, which can be easier to write when filtering large sets of elements.

Examples in the documentation: https://pandas.pydata.org/docs/user_guide/indexing.html#the-query-method

Here are a few examples.

In [36]:
df.query('person_income > 100000')

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
9,24.0,Associate,female,100684.0,3,RENT,35000.0,PERSONAL,8.90,0.35,2.0,544.0,No,1.0
11,22.0,High School,female,102985.0,0,RENT,35000.0,VENTURE,10.37,0.34,4.0,621.0,No,1.0
13,23.0,Bachelor,male,114860.0,3,RENT,35000.0,VENTURE,7.90,0.30,2.0,573.0,No,1.0
14,26.0,Master,male,130713.0,0,RENT,35000.0,EDUCATION,18.39,0.27,4.0,708.0,No,1.0
15,23.0,Associate,female,138998.0,0,RENT,35000.0,EDUCATION,7.90,0.25,4.0,583.0,No,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26247,28.0,High School,male,120995.0,2,MORTGAGE,10000.0,VENTURE,5.42,0.08,8.0,650.0,No,0.0
26249,33.0,Bachelor,male,121038.0,13,MORTGAGE,6000.0,PERSONAL,11.11,0.05,7.0,684.0,No,0.0
26251,32.0,Associate,male,121154.0,8,MORTGAGE,7000.0,HOMEIMPROVEMENT,7.14,0.06,9.0,620.0,No,0.0
26252,34.0,Bachelor,male,121188.0,13,MORTGAGE,9800.0,PERSONAL,7.14,0.08,8.0,723.0,No,0.0
26255,27.0,Bachelor,female,120932.0,1,MORTGAGE,3000.0,VENTURE,12.84,0.02,10.0,695.0,Yes,0.0

In [37]:
# Here, too, we can use the operators &, |, and ~
# As a reminder
# & - logical AND
# | - logical OR
# ~ - negation
display(df.query('person_education == "Doctorate" & person_age > 40'))
# code below 'person_education == ["Doctorate", "Master"] works like isin(["Doctorate", "Master"])
df.query('person_education == ["Doctorate", "Master"] & person_age > 40')

Empty DataFrame
Columns: [person_age, person_education, person_gender, person_income, person_emp_exp, person_home_ownership, loan_amnt, loan_intent, loan_int_rate, loan_percent_income, cb_person_cred_hist_length, credit_score, previous_loan_defaults_on_file, loan_status]
Index: []

Empty DataFrame
Columns: [person_age, person_education, person_gender, person_income, person_emp_exp, person_home_ownership, loan_amnt, loan_intent, loan_int_rate, loan_percent_income, cb_person_cred_hist_length, credit_score, previous_loan_defaults_on_file, loan_status]
Index: []

**Task 1**
Rename the column loan_amnt to loan_amount

In [38]:
df.head(3)

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,Master,female,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561.0,No,1.0
2,21.0,High School,female,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504.0,Yes,0.0
3,25.0,High School,female,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635.0,No,1.0

In [39]:
# Renaming the column and updating the dataframe
df = df.rename(columns={'loan_amnt': 'loan_amount'})

**Task 2**

From the data frame used in the examples (loan), display:

 - a) only the columns person_gender, person_age, and person_income,
- b) rows from 1000 through 2000 inclusive (this refers to consecutive rows in the dataset, not the index value),
- c) even-numbered rows,
- d) rows with an even value in the index column,
- e) the first and last columns with one function call.

In [40]:
# a) Only specific columns
task_2a = df[['person_gender', 'person_age', 'person_income']]

# b) Rows 1000 through 2000 inclusive (consecutive rows/positional)
# Using .iloc is zero-based, so 1000:2001 gets the 1000th through 2000th records
task_2b = df.iloc[1000:2001]

# c) Even-numbered rows (positional 0, 2, 4...)
task_2c = df.iloc[::2]

# d) Rows with an even value in the actual index column
task_2d = df[df.index % 2 == 0]

# e) The first and last columns with one function call, fancy slicing shows copy
task_2e = df.iloc[:, [0, -1]]

In [41]:
task_2a

      person_gender  person_age  person_income
1            female        22.0        71948.0
2            female        21.0        12282.0
3            female        25.0        12438.0
4            female        23.0        79753.0
5              male        24.0        66135.0
...             ...         ...            ...
26253        female        29.0        91131.0
26254        female        28.0        75625.0
26255        female        27.0       120932.0
26256        female        27.0        68809.0
26257          male        32.0        76472.0

[26257 rows x 3 columns]

In [42]:
task_2b

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1001,23.0,Bachelor,male,30059.0,0,MORTGAGE,1375.0,MEDICAL,11.11,0.05,4.0,506.0,No,1.0
1002,24.0,Bachelor,male,68258.0,2,RENT,18000.0,EDUCATION,13.48,0.26,3.0,671.0,No,1.0
1003,21.0,Bachelor,male,60821.0,0,RENT,18000.0,EDUCATION,14.74,0.30,2.0,530.0,No,1.0
1004,25.0,High School,male,70432.0,6,RENT,18000.0,VENTURE,11.01,0.26,4.0,609.0,No,1.0
1005,21.0,Bachelor,female,63842.0,0,RENT,18000.0,MEDICAL,19.69,0.28,2.0,678.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1997,21.0,Master,male,37264.0,0,RENT,14000.0,MEDICAL,10.65,0.38,2.0,545.0,No,1.0
1998,24.0,Associate,female,36841.0,4,RENT,14000.0,DEBTCONSOLIDATION,7.90,0.38,2.0,538.0,No,1.0
1999,24.0,Bachelor,male,37068.0,2,MORTGAGE,3075.0,DEBTCONSOLIDATION,11.01,0.08,4.0,521.0,Yes,0.0
2000,22.0,Bachelor,male,37513.0,0,RENT,14000.0,VENTURE,6.99,0.37,4.0,595.0,No,1.0
2001,23.0,Associate,female,36711.0,0,RENT,14000.0,MEDICAL,11.26,0.38,3.0,554.0,No,1.0

In [43]:
task_2c

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,Master,female,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561.0,No,1.0
3,25.0,High School,female,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635.0,No,1.0
5,24.0,Master,male,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586.0,No,1.0
7,26.0,Bachelor,female,93471.0,1,RENT,35000.0,EDUCATION,12.42,0.37,3.0,701.0,No,1.0
9,24.0,Associate,female,100684.0,3,RENT,35000.0,PERSONAL,8.90,0.35,2.0,544.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26249,33.0,Bachelor,male,121038.0,13,MORTGAGE,6000.0,PERSONAL,11.11,0.05,7.0,684.0,No,0.0
26251,32.0,Associate,male,121154.0,8,MORTGAGE,7000.0,HOMEIMPROVEMENT,7.14,0.06,9.0,620.0,No,0.0
26253,29.0,High School,female,91131.0,8,MORTGAGE,15000.0,MEDICAL,15.33,0.16,10.0,590.0,No,1.0
26255,27.0,Bachelor,female,120932.0,1,MORTGAGE,3000.0,VENTURE,12.84,0.02,10.0,695.0,Yes,0.0
26257,32.0,Bachelor,male,76472.0,7,RENT,14000.0,EDUCATION,6.00,NaN,NaN,NaN,NaN,NaN

In [44]:
task_2d

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
2,21.0,High School,female,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504.0,Yes,0.0
4,23.0,Bachelor,female,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675.0,No,1.0
6,21.0,High School,female,12951.0,0,OWN,2500.0,VENTURE,7.14,0.19,2.0,532.0,No,1.0
8,24.0,High School,female,95550.0,5,RENT,35000.0,MEDICAL,11.11,0.37,4.0,585.0,No,1.0
10,21.0,High School,female,12739.0,0,OWN,1600.0,VENTURE,14.74,0.13,3.0,640.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26248,30.0,Bachelor,male,91144.0,8,MORTGAGE,4800.0,MEDICAL,18.79,0.05,7.0,664.0,No,1.0
26250,31.0,Bachelor,female,90664.0,8,MORTGAGE,10000.0,MEDICAL,15.58,0.11,6.0,687.0,No,1.0
26252,34.0,Bachelor,male,121188.0,13,MORTGAGE,9800.0,PERSONAL,7.14,0.08,8.0,723.0,No,0.0
26254,28.0,Bachelor,female,75625.0,7,RENT,14000.0,VENTURE,10.99,0.19,10.0,647.0,No,0.0
26256,27.0,Bachelor,female,68809.0,3,RENT,14000.0,HOMEIMPROVEMENT,13.87,0.20,8.0,656.0,No,1.0

In [45]:
task_2e

       person_age  loan_status
1            22.0          1.0
2            21.0          0.0
3            25.0          1.0
4            23.0          1.0
5            24.0          1.0
...           ...          ...
26253        29.0          1.0
26254        28.0          0.0
26255        27.0          0.0
26256        27.0          1.0
26257        32.0          NaN

[26257 rows x 2 columns]

**Task 3**

From the same data frame, display data using filters (conditions):

- a) only women with a Master or Bachelor degree and loans between 50,000 and 70,000,
- b) all men with an education level other than Master and who own a home (person_home_ownership column = OWN),
- c) all individuals with a loan_percent_income value between 0.4 and 0.6,
- d) all loan amounts that are multiples of 10,000.

In [46]:
# a) Women with Master/Bachelor and loans between 50,000 and 70,000
task_3a = df.query("person_gender == 'female' & "
                   "person_education in ['Master', 'Bachelor'] & "
                   "loan_amount >= 50000 & loan_amount <= 70000")

# b) Men, education NOT Master, and own a home
task_3b = df.query("person_gender == 'male' & "
                   "person_education != 'Master' & "
                   "person_home_ownership == 'OWN'")

# c) loan_percent_income between 0.4 and 0.6
task_3c = df.query("loan_percent_income >= 0.4 & loan_percent_income <= 0.6")

# d) Loan amounts that are multiples of 10,000
task_3d = df[df['loan_amount'] % 10000 == 0]

In [47]:
task_3a

Empty DataFrame
Columns: [person_age, person_education, person_gender, person_income, person_emp_exp, person_home_ownership, loan_amount, loan_intent, loan_int_rate, loan_percent_income, cb_person_cred_hist_length, credit_score, previous_loan_defaults_on_file, loan_status]
Index: []

In [48]:
task_3b

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
28,23.0,High School,male,14293.0,0,OWN,1400.0,PERSONAL,9.32,0.10,3.0,607.0,No,0.0
31,21.0,High School,male,14858.0,0,OWN,2000.0,MEDICAL,11.12,0.13,3.0,589.0,No,1.0
36,21.0,Associate,male,15150.0,0,OWN,2500.0,EDUCATION,7.51,0.17,4.0,600.0,No,1.0
44,23.0,High School,male,361547.0,0,OWN,24250.0,EDUCATION,19.41,0.07,2.0,637.0,Yes,0.0
58,23.0,Bachelor,male,333399.0,1,OWN,35000.0,PERSONAL,11.01,0.10,4.0,609.0,No,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26133,28.0,Bachelor,male,115901.0,6,OWN,15000.0,EDUCATION,13.47,0.13,6.0,628.0,Yes,0.0
26170,29.0,Bachelor,male,117074.0,3,OWN,14600.0,MEDICAL,15.65,0.12,9.0,658.0,Yes,0.0
26193,31.0,Bachelor,male,118242.0,3,OWN,5100.0,HOMEIMPROVEMENT,6.03,0.04,6.0,640.0,Yes,0.0
26209,29.0,High School,male,39306.0,6,OWN,2100.0,HOMEIMPROVEMENT,6.91,0.05,5.0,662.0,Yes,0.0
26226,29.0,Bachelor,male,119600.0,4,OWN,9000.0,VENTURE,11.89,0.08,6.0,592.0,Yes,0.0

In [49]:
task_3c

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,Master,female,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561.0,No,1.0
3,25.0,High School,female,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635.0,No,1.0
4,23.0,Bachelor,female,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675.0,No,1.0
5,24.0,Master,male,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586.0,No,1.0
23,22.0,Master,female,79255.0,0,RENT,34000.0,EDUCATION,17.58,0.43,4.0,691.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25038,30.0,Associate,male,28108.0,6,RENT,12000.0,VENTURE,7.29,0.43,5.0,571.0,No,1.0
25041,32.0,High School,female,29697.0,12,RENT,12000.0,MEDICAL,11.01,0.40,8.0,700.0,No,1.0
25939,29.0,Associate,female,42250.0,4,OWN,20000.0,VENTURE,7.29,0.47,10.0,648.0,No,0.0
26026,27.0,Master,female,41220.0,6,OWN,21250.0,PERSONAL,8.88,0.52,6.0,666.0,Yes,0.0
26131,30.0,Bachelor,female,28849.0,6,RENT,14000.0,VENTURE,7.88,0.49,6.0,614.0,No,1.0

In [50]:
task_3d

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
16,23.0,Master,female,600891.0,5,MORTGAGE,30000.0,DEBTCONSOLIDATION,10.65,0.05,3.0,670.0,Yes,0.0
37,22.0,Bachelor,female,58868.0,0,RENT,30000.0,EDUCATION,18.39,0.51,2.0,606.0,No,1.0
38,24.0,High School,male,78026.0,3,RENT,30000.0,DEBTCONSOLIDATION,14.54,0.38,3.0,582.0,No,1.0
39,25.0,Bachelor,male,90785.0,4,RENT,30000.0,HOMEIMPROVEMENT,16.89,0.33,4.0,649.0,No,1.0
40,23.0,High School,female,86811.0,0,RENT,30000.0,DEBTCONSOLIDATION,11.01,0.35,4.0,602.0,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26215,29.0,Associate,male,118788.0,7,MORTGAGE,20000.0,VENTURE,8.88,0.17,9.0,652.0,Yes,0.0
26221,28.0,High School,female,119301.0,6,MORTGAGE,20000.0,VENTURE,14.84,0.17,9.0,607.0,Yes,0.0
26227,33.0,Bachelor,male,119460.0,11,MORTGAGE,10000.0,MEDICAL,11.01,0.08,7.0,582.0,No,0.0
26247,28.0,High School,male,120995.0,2,MORTGAGE,10000.0,VENTURE,5.42,0.08,8.0,650.0,No,0.0
26250,31.0,Bachelor,female,90664.0,8,MORTGAGE,10000.0,MEDICAL,15.58,0.11,6.0,687.0,No,1.0

## Tasks

1. Rename the column `loan_amnt` to `loan_amount`.

2. From the data frame used in the examples (loan), display:
   * a) only the columns `person_gender`, `person_age`, and `person_income`,
   * b) rows from 1000 through 2000 inclusive (this refers to consecutive rows in the dataset, not the index value),
   * c) even-numbered rows,
   * d) rows with an even value in the index column,
   * e) the first and last columns with one function call.

3. From the same data frame, display data using filters (conditions):
   * a) only women with a `Master` or `Bachelor` degree and loans between 50,000 and 70,000,
   * b) all men with an education level other than `Master` and who own a home (`person_home_ownership` column = `OWN`),
   * c) all individuals with a `loan_percent_income` value between 0.4 and 0.6,
   * d) all loan amounts that are multiples of 10,000.